export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

export const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST'
export const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS'
export const ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'ALL_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'ALL_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'ALL_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'ALL_DETAILS_REQUEST'
export const NEW_REVIEW_RESET = 'ALL_DETAILS_RESET'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERROR'